In [1]:
## Train for 50 epochs. First use only fine tuning on last layer
## Then compare with fine-tuning entire network
## TODO: 
## 0. Pre-process images
##      Resize images
##      Other pre-processing
## 0.1. Check image colors
## 1. Get mean and std of dataset - done
## Data augmentation - done
## 2. Train on Resnet-34
## 3. Train on efficient net b3
## 4. Train on mobilenet v3 large
## 5. Write a script to plot loss + accuracy graph
## 6. Get FLOPs
## 7. Get num layers - not needed?
## 8. Add class weights - done
## 9. Implement gradcam - done

In [6]:
import sys
sys.path.append('../src/')

In [7]:
%load_ext autoreload
%autoreload 2

from multilabel.train import train_model
from model import initialize_model
from utils import set_requires_grad, save_model
from multilabel.data import load_data
from plotting import plot_data_loader
from multilabel.eval import eval_model

In [1]:
import os
import copy
import time
import random
import pickle

import numpy as np
import pandas as pd
from PIL import Image
from pathlib import Path
from tqdm import tqdm

from sklearn.metrics import f1_score, confusion_matrix
from numpy.random import shuffle
import matplotlib.pyplot as plt

import torch
import torchvision
from torchvision.io import read_image
import torchvision.transforms as T
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, models, transforms
import torch.autograd.profiler as tprofiler
import torch.utils.data as td

plt.rcParams["savefig.bbox"] = 'tight'

In [2]:
seed = 42

random.seed(seed)

# pytorch RNGs
torch.manual_seed(seed)
torch.backends.cudnn.deterministic = True
if torch.cuda.is_available(): torch.cuda.manual_seed_all(seed)

# numpy RNG
np.random.seed(seed)

In [3]:
data_dir = "../data"
images_dir = "../data/processed"

In [4]:
# Get best num_workers
# for i in range(97):
#     start = time.time()
#     data_loader = load_data(images_dir,
#                                                                    batch_size = 96, 
#                                                                    input_size = 299, 
#                                                                    norm_arr = ([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
#                                                                    num_workers = i)
#     iter(data_loader['train']).next()[0].shape
#     print(f"{i}: {time.time()-start}")

In [8]:
# Check if GPU is available.
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

# Models options: resnet50, resnet34, inceptionv3, vgg16, mobile_net_v3_large, efficient_net_b1, efficient_net_b0, efficient_net_b3.
model_name = "mobile_net_v3_large"

# Number of classes.
num_classes = 20

# Batch Size.
batch_size = 32

# Epochs to train for.
num_epochs = 100

# Number of workers for data loader.
num_workers = 12

# Imagenet norm array passed as default value.
# norm_arr=([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
# Chest x-ray8 training dataset metrics 
norm_arr=((0.5989, 0.5510, 0.5175), (0.3358, 0.3330, 0.3377))

# Feature extract flag: False - Tune the whole model,
#                       True - Update only the reshaped layer parameters.
feature_extract = True

# Use pretrained flag: None - Use random weights
#                      String - Use pretrained weights given by String
#use_pretrained = models.EfficientNet_B3_Weights.IMAGENET1K_V1
use_pretrained = models.MobileNet_V3_Large_Weights.IMAGENET1K_V2

# Initialize the model for this run.
model_pyt, input_size = initialize_model(model_name, num_classes, feature_extract, use_pretrained=use_pretrained)

# lr start and end points for training.
lr_start = 0.01
lr_end = 0.001

# Print the model we just instantiated
#print(model_ft)

# Positive class weights.
pos_weight=torch.as_tensor([ 2.3509,  6.4782, 76.3264, 23.6350, 46.7897, 18.5694, 14.4224, 24.4805,
         1.1795,  0.6394,  9.1227, 80.2774,  0.8743,  2.1217,  7.2973, 87.3730,
        12.8151, 23.7444, 28.1492, 29.6749], dtype=torch.float)
pos_weight = pos_weight.to(device)

cuda:0


In [9]:
data_loaders = load_data(images_dir,
                         batch_size = batch_size, 
                         input_size = input_size, 
                         norm_arr = norm_arr,
                         num_workers = num_workers)

In [10]:
data_loaders['train'].dataset.classes

['Active',
 'Alert',
 'Amazed',
 'Amused',
 'Calm',
 'Cheerful',
 'Confident',
 'Conscious',
 'Creative',
 'Eager',
 'Educated',
 'Emotional',
 'Fashionable',
 'Feminine',
 'Inspired',
 'Loving',
 'Manly',
 'Persuaded',
 'Thrifty',
 'Youthful']

In [11]:
# plot_data_loader(data_loaders['train'], (2,2))

plot_data_loader(data_loader['train'], (2,2))

plot_data_loader(data_loader['test'], (2,2))

plot_data_loader(data_loader['val'], (2,2))

In [12]:
#model_pyt = torch.compile(model_pyt)
# Send model to GPU
model_pyt = model_pyt.to(device)

# Find parameters to be updated in this run.
# parameters with requires_grad = True.
params_to_update = model_pyt.parameters()
print("Params to learn:")
if feature_extract:
    params_to_update = []
    for name,param in model_pyt.named_parameters():
        if param.requires_grad == True:
            params_to_update.append(param)
            print("\t",name)
else:
    for name,param in model_pyt.named_parameters():
        if param.requires_grad == True:
            print("\t",name)

Params to learn:
	 classifier.3.weight
	 classifier.3.bias


In [13]:
# 17 min 1 epoch - 128 batch size - inception
# Efficientnet b0 - batch 96 - epoch 50 - num_workers 2 - flip, auto cont, sharp - 

In [14]:
# Observe that all parameters are being optimized
optimizer = optim.Adam(params_to_update, lr=lr_start)

# Learning rate scheduler.
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_epochs, eta_min=lr_end,
                                                 last_epoch=-1)


# Setup the loss fxn
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

# Train and evaluate
model_pyt, prof, val_history, train_history = train_model(device, model_pyt, data_loaders, 
                                                            optimizer, scheduler,
                                                            criterion, 
                                                            num_epochs=num_epochs,
                                                            num_classes=num_classes,
                                                            is_inception=(model_name=="inceptionv3"),
                                                            profiler=False)

Epoch 1/100
----------
Epoch [1/100], Step [100/348], Loss: 1.1874, Accuracy: 86.56%
Epoch [1/100], Step [200/348], Loss: 0.6908, Accuracy: 85.78%
Epoch [1/100], Step [300/348], Loss: 0.9048, Accuracy: 82.50%
train Loss: 0.9026 Acc: 84.70%
Epoch [1/100], Step [100/348], Loss: 0.8373, Accuracy: 85.78%
val Loss: 0.9438 Acc: 83.96%

Epoch 2/100
----------
Epoch [2/100], Step [100/348], Loss: 0.6757, Accuracy: 81.25%
Epoch [2/100], Step [200/348], Loss: 0.8419, Accuracy: 84.06%
Epoch [2/100], Step [300/348], Loss: 0.9459, Accuracy: 80.94%
train Loss: 0.8839 Acc: 83.41%
Epoch [2/100], Step [100/348], Loss: 0.6907, Accuracy: 87.19%
val Loss: 0.9818 Acc: 85.16%

Epoch 3/100
----------
Epoch [3/100], Step [100/348], Loss: 0.8125, Accuracy: 82.50%
Epoch [3/100], Step [200/348], Loss: 0.8811, Accuracy: 85.31%
Epoch [3/100], Step [300/348], Loss: 0.8539, Accuracy: 82.81%
train Loss: 0.8930 Acc: 83.33%
Epoch [3/100], Step [100/348], Loss: 0.6185, Accuracy: 85.31%
val Loss: 0.9950 Acc: 84.65%

Epoc

In [15]:
dataset_name = 'ads'

In [16]:
save_model(model_pyt.state_dict(), '../models/', 
           f'augmented_{model_name}_{dataset_name}_{num_epochs}_{batch_size}_{lr_start}_{lr_end}_model_weights.pth')

True

In [17]:
eval_metrics = eval_model(device=device, model=model_pyt, test_loader=data_loaders['test'], is_inception=(model_name=="inceptionv3"), num_classes=7)

In [18]:
for i, v in eval_metrics.items():
    print(f"{i}: {v}")

acc: 2.5702355295566504
f1: 0.1685007280607184
cm: [[[3170   29]
  [ 461   52]]

 [[3226  257]
  [ 186   43]]

 [[3472  215]
  [  20    5]]

 [[3513  139]
  [  55    5]]

 [[3441  227]
  [  39    5]]

 [[3384  243]
  [  75   10]]

 [[3487  106]
  [ 116    3]]

 [[3383  258]
  [  65    6]]

 [[2900   27]
  [ 758   27]]

 [[2722   39]
  [ 698  253]]

 [[3281  274]
  [ 102   55]]

 [[3455  236]
  [  16    5]]

 [[2809   82]
  [ 503  318]]

 [[3058  152]
  [ 259  243]]

 [[3246  249]
  [ 144   73]]

 [[3336  355]
  [  16    5]]

 [[3426  157]
  [  94   35]]

 [[3453  171]
  [  76   12]]

 [[3432  221]
  [  16   43]]

 [[3372  284]
  [  35   21]]]
outputs: [[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
targets: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [19]:
with open(f'../models/val_history_augmented_{model_name}_{dataset_name}_{num_epochs}_{batch_size}_{lr_start}_{lr_end}_.pickle', 'wb') as handle:
    pickle.dump(val_history, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open(f'../models/train_history_augmented_{model_name}_{dataset_name}_{num_epochs}_{batch_size}_{lr_start}_{lr_end}_.pickle', 'wb') as handle:
    pickle.dump(train_history, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open(f'../models/eval_metrics_augmented_{model_name}_{dataset_name}_{num_epochs}_{batch_size}_{lr_start}_{lr_end}_.pickle', 'wb') as handle:
    pickle.dump(eval_metrics, handle, protocol=pickle.HIGHEST_PROTOCOL)

#with open('filename.pickle', 'rb') as handle:
#    b = pickle.load(handle)

In [ ]:
#print(prof.key_averages(group_by_stack_n=5).table(sort_by='self_cpu_time_total', row_limit=50))

In [9]:
# Plot the training curves of validation accuracy vs. number
#  of training epochs for the transfer learning method and
#  the model trained from scratch
# vhist = []
# vhist = [h.cpu().numpy() for h in val_acc_history]
# thist = []
# thist = [h.cpu().numpy() for h in train_acc_history]

# plt.title("Accuracy vs. Number of Training Epochs")
# plt.xlabel("Training Epochs")
# plt.ylabel("Accuracy")
# #plt.plot(range(1,num_epochs+1),ohist,label="Pretrained")
# plt.plot(range(1,num_epochs+1),vhist,label="Validation")
# plt.plot(range(1,num_epochs+1),thist,label="Training")
# plt.ylim((0,1.))
# plt.xticks(np.arange(1, num_epochs+1, 1.0))
# plt.legend()
# plt.show()

In [8]:
# Plot the training curves of validation accuracy vs. number
#  of training epochs for the transfer learning method and
#  the model trained from scratch
# vhist = []
# vhist = [h for h in val_loss_history]
# thist = []
# thist = [h for h in train_loss_history]

# plt.title("Loss vs. Number of Training Epochs")
# plt.xlabel("Training Epochs")
# plt.ylabel("Loss")
# #plt.plot(range(1,num_epochs+1),ohist,label="Pretrained")
# plt.plot(range(1,num_epochs+1),vhist,label="Validation")
# plt.plot(range(1,num_epochs+1),thist,label="Training")
# plt.ylim((0,1.))
# plt.xticks(np.arange(1, num_epochs+1, 1.0))
# plt.legend()
# plt.show()